[package]
name = "prolock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
dirs = "5.0.1"
fd-lock = "4.0.2"
pwsec = "0.5.1"
secstr = "0.5.1"
sequential = { version = "0.5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
