[package]
name = "prolock"
version = "1.2.0"

edition = "2024"
authors = ["emabee <meinolf.block-hd@t-online.de>"]
description = """
ProLock is a tool for securely storing secrets like passwords and plain text snippets
in a password-protected file.
"""
keywords = ["security", "encryption"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emabee/rust-prolock"
rust-version = "1.98.0"

[package.metadata.bundle]
name = "ProLock"
identifier = "com.github.emabee.prolock"
icon = ["resources/logo.icns"]
copyright = "Copyright (c) Meinolf Block 2025. All rights reserved."
category = "public.app-category.utilities"
short_description = "a tool for securely storing secrets"
long_description = """
A tool for conveniently storing secrets well encrypted into a file in the local file system.
There is no interaction with any cloud service, nor with the browser or any other application.
It is a simple, but effective way to keep your secrets safe.
It is written in Rust and uses the `egui` framework for the GUI.
It is cross-platform and works on Linux, macOS, and Windows.
It is open source and licensed under the MIT or Apache-2.0 license.
"""

[profile.release]
strip = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["cargo"] }
dirs = "7.0"
#### vvvv only temporarily, for embedded file_dialog
# fetch user folders
directories = "6.0"
# canonicalize paths
dunce = "1.0.5"
# fetch disks
sysinfo = { version = "0.39", default-features = false, features = ["disk"] }
# meta-data storage
indexmap = { version = "2.7.0", features = ["serde"] }
# info panel meta-data display
image-meta = { version = "0.1.2" }
chrono = { version = "0.4.39" }
#### ^^^^
egui = { version = "0.36" }
egui_extras = { version = "0.36", features = ["file", "image"] }
egui_modal_with_titlebar = "0.10"
# egui-file-dialog = { path = "../egui-file-dialog-modal" }
eframe = { version = "0.36" }
fd-lock = "4.0.2"
flexi_logger = { version = "0.31", features = ["buffer_writer"] }
fuzzy-matcher = "0.3"
image = { version = "0.25", features = ["png"] }
jiff = { version = "0.2", features = ["serde"] }
log = "0.4"
oxilangtag = "0.1"
pwsec = "0.6"                                                     # { path = "../pwsec" }
rand = "0.10"
rust-i18n = "4.2"
secstr = "0.5"
sequential = { version = "0.5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sys-locale = "0.3"
tempfile = "3.15"
whoami = "2.1.1"

[dev-dependencies]
tempdir = "0.3"
