name: Build and test ProLock

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # (jobs are run in parallel by default)

  clippy_check:
      # Precondition:
      # Github repo -> Settings -> Actions -> General -> Workflow permissions -> Read and write permissions for Actions
      name: Run Clippy
      runs-on: ubuntu-latest

      steps:
        - name: checkout the repo
          uses: actions/checkout@v4

        # - name: install nightly rust toolchain with clippy
        #   uses: actions-rs/toolchain@v1
        #   with:
        #       toolchain: nightly
        #       components: clippy
        #       override: true


        - name: install nightly rust toolchain with clippy
          run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy

        - name: run clippy
          run: cargo +nightly clippy --all-targets --all-features


  build_and_test:
      name: fmt, build, test
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest, macOS-13]

      steps:
        - name: checkout the repo
          uses: actions/checkout@v4
      
        - name: install stable rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable

        - name: check fmt
          uses: actions-rs/cargo@v1
          with:
            command: fmt
            args: --check

        - name: debug build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --verbose

        - name: run tests
          uses: actions-rs/cargo@v1
          with:
            command: test
