name: Build and test ProLock

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # (jobs are run in parallel by default)

  clippy_check:
      # Precondition:
      # Github repo -> Settings -> Actions -> General -> Workflow permissions -> Read and write permissions for Actions
      name: Run Clippy
      runs-on: ubuntu-latest

      steps:
        - name: checkout the repo
          uses: actions/checkout@v4

        - name: install nightly rust toolchain with clippy
          run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy

        - name: run clippy
          run: cargo +nightly clippy --all-targets --all-features


  build_and_test:
      name: fmt, build, test
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest, macOS-13]

      steps:
        - name: checkout the repo
          uses: actions/checkout@v4
      
        - name: check fmt
          run: cargo fmt --check

        - name: debug build
          run: cargo build --verbose

        - name: run tests
          run: cargo test
