name: Build and test ProLock

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
      # Precondition:
      # Github repo -> Settings -> Actions -> General -> Workflow permissions -> Read and write permissions for Actions
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: nightly
              components: clippy
              override: true

        - uses: actions-rs/clippy-check@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --all-features


  build_and_test:
    name: Check fmt, build and test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macOS-13]

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      - uses: actions-rs/cargo@v1
        with:
          command: test
