name: Build and test ProLock

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macOS-13]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: clippy
      run: cargo +nightly clippy -- -D warnings
    - name: Run tests
      run: cargo +stable test --verbose

#  publish:
#  
#    needs: build

