name: MacOS Build (linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Build linux binary
        run: |
          cargo build --release

      - name: Upload linux binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProLock for linux
          path: target/release/prolock
