name: MacOS Build (windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Build Windows executable
        run: |
          cargo build --release

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProLock.exe for Windows
          path: target/release/proLock.exe
